import { useEffect, useMemo, useState } from 'react';
import { Check, ClipboardList, Send, ThumbsDown, ThumbsUp } from 'lucide-react';
import { useNavigate } from 'react-router-dom';
import { useAuth } from '../auth';
import api from '../api';
import PageTitle from '../components/PageTitle';
import StatusBadge from '../components/StatusBadge';

export default function MyWork(){
  const {user}=useAuth();const navigate=useNavigate();const[projects,setProjects]=useState([]);const[error,setError]=useState('');
  function load(){api.get('/projects').then(r=>setProjects(r.data)).catch(e=>setError(e.response?.data?.message||'Could not load work'))};useEffect(load,[]);
  const rows=useMemo(()=>{
    const out=[];projects.forEach(p=>p.stages?.forEach(s=>s.tasks?.forEach(t=>{if(user.role==='Site Engineer'&&t.assignedTo===user.id)out.push({type:'task',project:p,stage:s,task:t});if(user.role==='Manager'&&(t.status==='Pending Approval'&&((s.ownerUserId===user.id)||(p.projectManagerId===user.id))))out.push({type:'taskApproval',project:p,stage:s,task:t})}))); 
    if(user.role==='Tender Executive') projects.forEach(p=>p.stages?.forEach(s=>{if(s.stageApprovalStatus==='Pending Approval')out.push({type:'stageApproval',project:p,stage:s})}));
    return out;
  },[projects,user]);
  async function update(row,approved){try{if(row.type==='taskApproval')await api.put(`/projects/${row.project._id}/stages/${row.stage._id}/tasks/${row.task._id}`,{status:approved?'Completed':'Rejected'});if(row.type==='stageApproval')await api.post(`/projects/${row.project._id}/stages/${row.stage._id}/decision`,{approved});load()}catch(e){setError(e.response?.data?.message||'Action failed')}}
  async function complete(row){try{await api.put(`/projects/${row.project._id}/stages/${row.stage._id}/tasks/${row.task._id}`,{status:'Completed'});load()}catch(e){setError(e.response?.data?.message||'Action failed')}}
  return <div><PageTitle eyebrow={user.role==='Tender Executive'?'CONTROL DESK':'MY WORK'} title={user.role==='Tender Executive'?'Approvals':'My work queue'} subtitle={user.role==='Tender Executive'?'Stage approvals waiting for Tender Executive review.':user.role==='Manager'?'Approve engineer sub-steps and move stages forward.':'Complete assigned sub-steps; completed work goes to your manager for approval.'}/>{error&&<div className="error-box">{error}</div>}<section className="panel"><div className="panel-head"><div><h3>{rows.length} items need attention</h3><p>Open the project for the full workflow context.</p></div></div><div className="work-queue">{rows.map((r,i)=><div className="queue-row" key={`${r.project._id}-${r.stage._id}-${r.task?._id||i}`}><div className="queue-icon"><ClipboardList size={18}/></div><div className="queue-main"><span className="eyebrow">{r.type==='stageApproval'?'STAGE APPROVAL':r.type==='taskApproval'?'TASK APPROVAL':'ASSIGNED TASK'}</span><strong>{r.task?.title||r.stage.name}</strong><small>{r.project.projectId} · {r.project.name} · Stage {r.stage.order}: {r.stage.name}</small>{r.task?.description&&<p>{r.task.description}</p>}</div><div className="queue-action">{r.type==='task'&&<><StatusBadge status={r.task.status}/><button className="primary-btn small" disabled={r.task.status==='Pending Approval'||r.task.status==='Completed'} onClick={()=>complete(r)}>{r.task.status==='Pending Approval'?'Pending approval':<><Check size={15}/> Mark complete</>}</button></>}{r.type==='taskApproval'&&<><button className="small-btn success" onClick={()=>update(r,true)}><ThumbsUp size={14}/> Approve</button><button className="small-btn danger-outline" onClick={()=>update(r,false)}><ThumbsDown size={14}/> Reject</button></>}{r.type==='stageApproval'&&<><button className="small-btn" onClick={()=>navigate(`/projects/${r.project._id}`)}>Open</button><button className="small-btn success" onClick={()=>update(r,true)}><ThumbsUp size={14}/> Approve</button><button className="small-btn danger-outline" onClick={()=>update(r,false)}><ThumbsDown size={14}/> Send back</button></>}</div></div>)}{!rows.length&&<div className="empty"><Send size={22}/><strong>Nothing waiting here.</strong><span>New tasks and approvals will appear here automatically.</span></div>}</div></section></div>
}
