import { useEffect, useMemo, useState } from 'react';
import { ArrowLeft, Check, ChevronRight, ClipboardCheck, Package, Plus, Send, ThumbsDown, ThumbsUp, Wrench } from 'lucide-react';
import { useNavigate, useParams } from 'react-router-dom';
import { useAuth } from '../auth';
import api from '../api';
import PageTitle from '../components/PageTitle';
import StatusBadge from '../components/StatusBadge';
import Modal from '../components/Modal';
import StageTimeline from '../components/StageTimeline';

export default function ProjectDetails(){
  const {id}=useParams(); const navigate=useNavigate(); const {user}=useAuth(); const [p,setP]=useState(null); const [masters,setMasters]=useState(null); const [error,setError]=useState(''); const [tab,setTab]=useState('stages');
  const [taskOpen,setTaskOpen]=useState(false), [taskStage,setTaskStage]=useState(null); const [taskForm,setTaskForm]=useState({title:'',description:'',assignedTo:'',dueDate:''});
  const [boqOpen,setBoqOpen]=useState(false), [boqAction,setBoqAction]=useState(null), [boqForm,setBoqForm]=useState({qty:1,reason:''});
  const [busy,setBusy]=useState(false);
  function load(){ Promise.all([api.get(`/projects/${id}`),api.get('/masters')]).then(([a,b])=>{setP(a.data);setMasters(b.data)}).catch(e=>setError(e.response?.data?.message||'Could not load project')); }
  useEffect(load, [id]);
  const myStages=useMemo(()=>p?.stages?.filter(s=>s.ownerUserId===user?.id || p.projectManagerId===user?.id)||[],[p,user]);
  const allTasks=useMemo(()=>p?.stages?.flatMap(s=>s.tasks?.map(t=>({...t,stageId:s._id,stageName:s.name}))||[])||[],[p]);

  async function refreshAfter(fn){setBusy(true);setError('');try{const r=await fn();setP(r.data)}catch(e){setError(e.response?.data?.message||'Action failed')}finally{setBusy(false)}}
  async function addTask(){await refreshAfter(()=>api.post(`/projects/${id}/stages/${taskStage._id}/tasks`,taskForm));setTaskOpen(false);setTaskForm({title:'',description:'',assignedTo:'',dueDate:''})}
  async function updateTask(stageId,taskId,status,notes){await refreshAfter(()=>api.put(`/projects/${id}/stages/${stageId}/tasks/${taskId}`,{status,notes}))}
  async function submitStage(stage){await refreshAfter(()=>api.post(`/projects/${id}/stages/${stage._id}/submit`))}
  async function decideStage(stage,approved){await refreshAfter(()=>api.post(`/projects/${id}/stages/${stage._id}/decision`,{approved}))}
  async function boqSubmit(){ if(!boqAction)return; const fn=boqAction.type==='use'?()=>api.post(`/projects/${id}/boq/${boqAction.item._id}/use`,{qty:Number(boqForm.qty)}):()=>api.post(`/projects/${id}/boq/${boqAction.item._id}/amend`,{qty:Number(boqForm.qty),reason:boqForm.reason}); await refreshAfter(fn); setBoqOpen(false); setBoqForm({qty:1,reason:''}); }
  async function amendmentDecision(item, amendmentId, approved){await refreshAfter(()=>api.post(`/projects/${id}/boq/${item._id}/amendments/${amendmentId}/decision`,{approved}))}

  if(!p) return <div className="center-loader">Loading project…</div>;
  const total=p.stages?.length||0, approved=p.stages?.filter(s=>s.stageApprovalStatus==='Approved').length||0, progress=total?Math.round(approved/total*100):0;
  const canManager=user.role==='Manager' && myStages.length>0, canEngineer=user.role==='Site Engineer'; const pendingStage=p.stages?.filter(s=>s.stageApprovalStatus==='Pending Approval')||[];

  return <div>
    <PageTitle eyebrow={`${p.projectId} · ${p.clientName||'Client'}`} title={p.name} subtitle={`${p.projectType} · Project Manager: ${p.projectManagerName||'Unassigned'}`} action={<button className="secondary-btn" onClick={()=>navigate('/projects')}><ArrowLeft size={17}/> Projects</button>} />
    {error&&<div className="error-box">{error}</div>}
    <section className="hero-panel panel"><div className="hero-left"><div className="hero-chips"><StatusBadge status={p.priority}/><StatusBadge status={p.status}/></div><h3>{p.remarks||'No project remarks added.'}</h3><div className="hero-meta"><span>Start: <b>{p.estStartDate?new Date(p.estStartDate).toLocaleDateString():'—'}</b></span><span>Expected completion: <b>{p.expectedCompletionDate?new Date(p.expectedCompletionDate).toLocaleDateString():'—'}</b></span><span>Approved stages: <b>{approved}/{total}</b></span></div></div><div className="hero-progress"><div className="progress-ring"><strong>{progress}%</strong><span>stage progress</span></div></div></section>

    <div className="tabs"><button className={tab==='stages'?'active':''} onClick={()=>setTab('stages')}><ClipboardCheck size={16}/> Stages & tasks</button><button className={tab==='boq'?'active':''} onClick={()=>setTab('boq')}><Package size={16}/> BOQ / inventory</button></div>

    {tab==='stages' && <div className="details-grid"><section className="panel"><div className="panel-head"><div><h3>Stage workflow</h3><p>Matches the first Excel sheet, but each stage now has an owner and task workflow.</p></div></div><StageTimeline stages={p.stages}/></section>
      <section className="panel work-panel"><div className="panel-head"><div><h3>{user.role==='Site Engineer'?'My assigned work':user.role==='Manager'?'Stage control':'Approval queue'}</h3><p>{user.role==='Tender Executive'?'Review stage and BOQ approvals.':user.role==='Manager'?'Create sub-steps, approve engineer work and submit completed stages.':'Complete assigned tasks and report material usage.'}</p></div></div>
        {user.role==='Tender Executive' && pendingStage.length>0 && <div className="action-block approval-block"><div className="block-title"><span>Stage approvals</span><b>{pendingStage.length}</b></div>{pendingStage.map(s=><div className="action-row" key={s._id}><div><strong>{s.name}</strong><small>{s.ownerName}</small></div><div className="actions"><button className="small-btn success" onClick={()=>decideStage(s,true)} disabled={busy}><ThumbsUp size={14}/> Approve</button><button className="small-btn danger-outline" onClick={()=>decideStage(s,false)} disabled={busy}><ThumbsDown size={14}/> Send back</button></div></div>)}</div>}
        {canManager && <div className="assigned-stage-list">{myStages.map(s=><div className="stage-work-card" key={s._id}><div className="stage-work-head"><div><span className="eyebrow">STAGE {s.order}</span><h4>{s.name}</h4></div><StatusBadge status={s.stageApprovalStatus==='Pending Approval'?'Pending Approval':s.status}/></div><div className="task-list">{(s.tasks||[]).map(t=><div className="task-row" key={t._id}><div><strong>{t.title}</strong><small>{t.assignedToName||'Unassigned'} · {t.status}</small></div>{t.status==='Pending Approval'?<div className="actions"><button className="small-btn success" onClick={()=>updateTask(s._id,t._id,'Completed',t.notes)} disabled={busy}><Check size={14}/> Approve</button><button className="small-btn danger-outline" onClick={()=>updateTask(s._id,t._id,'Rejected',t.notes)} disabled={busy}><ThumbsDown size={14}/> Reject</button></div>:<StatusBadge status={t.status}/>}</div>)}{!s.tasks?.length&&<div className="empty small">No sub-steps yet.</div>}</div><div className="stage-work-actions"><button className="secondary-btn small" onClick={()=>{setTaskStage(s);setTaskOpen(true)}}><Plus size={15}/> Add sub-step</button>{(s.tasks||[]).every(t=>t.status==='Completed')&&<button className="primary-btn small" onClick={()=>submitStage(s)} disabled={busy}><Send size={15}/> Submit stage</button>}</div></div>)}</div>}
        {user.role==='Site Engineer' && <div className="assigned-stage-list">{p.stages.map(s=>{const mine=(s.tasks||[]).filter(t=>t.assignedTo===user.id); if(!mine.length)return null; return <div className="stage-work-card" key={s._id}><div className="stage-work-head"><div><span className="eyebrow">STAGE {s.order}</span><h4>{s.name}</h4></div><StatusBadge status={s.status}/></div>{mine.map(t=><div className="engineer-task" key={t._id}><div><strong>{t.title}</strong><p>{t.description||'No task description.'}</p><small>Due: {t.dueDate?new Date(t.dueDate).toLocaleDateString():'Not set'}</small></div><button className={t.status==='Pending Approval'?'secondary-btn small':'primary-btn small'} disabled={busy||t.status==='Pending Approval'||t.status==='Completed'} onClick={()=>updateTask(s._id,t._id,'Completed',t.notes)}>{t.status==='Pending Approval'?'Awaiting approval':t.status==='Completed'?'Completed':'Mark complete'}</button></div>)}</div>})}{!allTasks.some(t=>t.assignedTo===user.id)&&<div className="empty">No tasks assigned in this project.</div>}</div>}
      </section>
    </div>}

    {tab==='boq' && <section className="panel"><div className="panel-head"><div><h3>BOQ / inventory ledger</h3><p>Planned quantity, used quantity and amendment requests replace manual Excel calculations.</p></div><div className="inventory-total"><Wrench size={16}/> {p.boq?.length||0} tracked items</div></div><div className="boq-table"><div className="boq-table-head"><span>Item</span><span>Planned</span><span>Used</span><span>Available</span><span>Amendments</span><span>Actions</span></div>{(p.boq||[]).map(item=>{const approvedAdd=(item.amendments||[]).filter(a=>a.status==='Approved').reduce((s,a)=>s+a.qty,0);const available=item.qtyPlanned+approvedAdd-item.qtyUsed;return <div className="boq-table-row" key={item._id}><span><strong>{item.item}</strong><small>{item.unit}</small></span><span>{item.qtyPlanned}</span><span>{item.qtyUsed}</span><span><b>{available}</b></span><span>{item.amendments?.length||0}</span><span className="actions"><button className="small-btn" onClick={()=>{setBoqAction({type:'use',item});setBoqOpen(true)}}>Use item</button><button className="small-btn" onClick={()=>{setBoqAction({type:'amend',item});setBoqOpen(true)}}>Request amendment</button></span></div>})}{!p.boq?.length&&<div className="empty">No BOQ items configured for this project.</div>}</div>
      {p.boq?.some(x=>x.amendments?.length) && <div className="amendment-list"><div className="subhead">Amendment requests</div>{p.boq.flatMap(item=>(item.amendments||[]).map(a=><div className="amendment-row" key={a._id}><div><strong>{item.item}</strong><small>+{a.qty} · {a.reason} · by {a.requestedByName}</small></div><div className="actions"><StatusBadge status={a.status}/>{user.role==='Tender Executive'&&a.status==='Pending'&&<><button className="small-btn success" onClick={()=>amendmentDecision(item,a._id,true)}><ThumbsUp size={14}/> Approve</button><button className="small-btn danger-outline" onClick={()=>amendmentDecision(item,a._id,false)}><ThumbsDown size={14}/> Reject</button></>}</div></div>))}</div>}
    </section>}

    <Modal open={taskOpen} title={`Add sub-step · ${taskStage?.name||''}`} onClose={()=>setTaskOpen(false)}>
      <div className="field-grid"><label>Task title<input value={taskForm.title} onChange={e=>setTaskForm({...taskForm,title:e.target.value})} placeholder="Prepare survey report"/></label><label>Assign to Site Engineer<select value={taskForm.assignedTo} onChange={e=>setTaskForm({...taskForm,assignedTo:e.target.value})}><option value="">Select engineer</option>{(masters?.users||[]).filter(u=>u.role==='Site Engineer').map(u=><option key={u._id} value={u._id}>{u.name}</option>)}</select></label><label>Due date<input type="date" value={taskForm.dueDate} onChange={e=>setTaskForm({...taskForm,dueDate:e.target.value})}/></label><label className="full">Description<textarea rows="3" value={taskForm.description} onChange={e=>setTaskForm({...taskForm,description:e.target.value})}/></label></div><div className="modal-actions"><button className="secondary-btn" onClick={()=>setTaskOpen(false)}>Cancel</button><button className="primary-btn" onClick={addTask}><Plus size={16}/> Add task</button></div>
    </Modal>
    <Modal open={boqOpen} title={boqAction?.type==='use'?'Record material usage':'Request BOQ amendment'} onClose={()=>setBoqOpen(false)}><p className="modal-note"><strong>{boqAction?.item?.item}</strong> · {boqAction?.item?.unit}</p><div className="field-grid"><label>Quantity<input type="number" min="0.1" step="0.1" value={boqForm.qty} onChange={e=>setBoqForm({...boqForm,qty:e.target.value})}/></label>{boqAction?.type==='amend'&&<label className="full">Reason<textarea rows="3" value={boqForm.reason} onChange={e=>setBoqForm({...boqForm,reason:e.target.value})} placeholder="Additional quantity required because…"/></label>}</div><div className="modal-actions"><button className="secondary-btn" onClick={()=>setBoqOpen(false)}>Cancel</button><button className="primary-btn" onClick={boqSubmit}>{boqAction?.type==='use'?'Save usage':'Submit amendment'}</button></div></Modal>
  </div>
}
